export enum RouterEnum {
  MAGAZINE_LIST = 'MAGAZINE_LIST',
  MAGAZINE_DETAIL = 'MAGAZINE_DETAIL',
  MAGAZINE_EDIT = 'MAGAZINE_EDIT',
  MAGAZINE_NEW = 'MAGAZINE_NEW',

  OPTIC_NEW = 'OPTIC_NEW',
  OPTIC_LIST = 'OPTIC_LIST',
  OPTIC_DETAIL = 'OPTIC_DETAIL',
  OPTIC_EDIT = 'OPTIC_EDIT'
}
