export enum RouterEnum {
  MAGAZINE_LIST = 'MAGAZINE_LIST',
  MAGAZINE_DETAIL = 'MAGAZINE_DETAIL',
  MAGAZINE_EDIT = 'MAGAZINE_EDIT',
  MAGAZINE_NEW = 'MAGAZINE_NEW',

  OPTIC_NEW = 'OPTIC_NEW',
  OPTIC_LIST = 'OPTIC_LIST',
  OPTIC_DETAIL = 'OPTIC_DETAIL',
  OPTIC_EDIT = 'OPTIC_EDIT',

  OPTIC_COLLAR_NEW = 'OPTIC_COLLAR_NEW',
  OPTIC_COLLAR_LIST = 'OPTIC_COLLAR_LIST',

  AMMUNITION_NEW = 'AMMUNITION_NEW',
  AMMUNITION_LIST = 'AMMUNITION_LIST',
  AMMUNITION_DETAIL = 'AMMUNITION_DETAIL',
  AMMUNITION_EDIT = 'AMMUNITION_EDIT',

  WEAPON_NEW = 'WEAPON_NEW',
  WEAPON_LIST = 'WEAPON_LIST',
  WEAPON_DETAIL = 'WEAPON_DETAIL',
  WEAPON_EDIT = 'WEAPON_EDIT',

  FACTORY_NEW = 'FACTORY_NEW',
  FACTORY_LIST = 'FACTORY_LIST',

  COLOR_NEW = 'COLOR_NEW',
  MATERIAL_NEW = 'MATERIAL_NEW',
  HEAD_TYPE_NEW = 'HEAD_TYPE_NEW',
  BODY_TYPE_NEW = 'BODY_TYPE_NEW',
  THREADED_SIZE_NEW = 'THREADED_SIZE_NEW',
  WEAPON_TYPE_NEW = 'WEAPON_TYPE_NEW',
  CALIBER_NEW = 'CALIBER_NEW'
}
