export type PriceableObjectType =
  | 'AMMUNITION'
  | 'HANDGUN'
  | 'OPTIC'
  | 'OPTIC_COLLAR'
  | 'RIFFLE'
  | 'RDS'
  | 'MAGAZINE'
export type StockableObjectType =
  | 'AMMUNITION'
  | 'HANDGUN'
  | 'OPTIC'
  | 'OPTIC_COLLAR'
  | 'RIFFLE'
  | 'RDS'
  | 'MAGAZINE'
  | 'DEFAULT'
