export enum PublicRouterEnum {
  HOME = 'HOME',

  PUBLIC_RIFFLE_LIST = 'PUBLIC_RIFFLE_LIST',
  PUBLIC_RIFFLE_DETAIL = 'PUBLIC_RIFFLE_DETAIL',

  PUBLIC_HANDGUN_LIST = 'PUBLIC_HANDGUN_LIST',
  PUBLIC_HANDGUN_DETAIL = 'PUBLIC_HANDGUN_DETAIL',

  PUBLIC_AMMUNITION_LIST = 'PUBLIC_AMMUNITION_LIST',
  PUBLIC_AMMUNITION_DETAIL = 'PUBLIC_AMMUNITION_DETAIL',

  PUBLIC_OPTIC_LIST = 'PUBLIC_OPTIC_LIST',
  PUBLIC_OPTIC_DETAIL = 'PUBLIC_OPTIC_DETAIL',

  PUBLIC_OPTIC_COLLAR_LIST = 'PUBLIC_OPTIC_COLLAR_LIST',
  PUBLIC_OPTIC_COLLAR_DETAIL = 'PUBLIC_OPTIC_COLLAR_DETAIL',

  PUBLIC_RDS_DETAIL = 'PUBLIC_RDS_DETAIL',
  PUBLIC_RDS_LIST = 'PUBLIC_RDS_LIST',

  PUBLIC_MAGAZINE_LIST = 'PUBLIC_MAGAZINE_LIST',
  PUBLIC_MAGAZINE_DETAIL = 'PUBLIC_MAGAZINE_DETAIL',

  CART = 'CART',
  CART_ADDRESS = 'CART_ADDRESS',
  CART_PAYMENT_ADDRESS = 'CART_PAYMENT_ADDRESS',
  CART_NEW_ADDRESS = 'CART_NEW_ADDRESS',
  CART_RESUME = 'CART_RESUME',

  USER_NEW_ADDRESS = 'USER_NEW_ADDRESS'
}
