export enum PublicRouterEnum {
  HOME = 'HOME',
  PUBLIC_RIFFLE_LIST = 'PUBLIC_RIFFLE_LIST',
  PUBLIC_HANDGUN_LIST = 'PUBLIC_HANDGUN_LIST',
  PUBLIC_RIFFLE_DETAIL = 'PUBLIC_RIFFLE_DETAIL',
  PUBLIC_HANDGUN_DETAIL = 'PUBLIC_HANDGUN_DETAIL',
  PUBLIC_AMMUNITION_DETAIL = 'PUBLIC_AMMUNITION_DETAIL',
  PUBLIC_RDS_DETAIL = 'PUBLIC_RDS_DETAIL',
  PUBLIC_OPTIC_DETAIL = 'PUBLIC_OPTIC_DETAIL',
  PUBLIC_OPTIC_LIST = 'PUBLIC_OPTIC_LIST',
  PUBLIC_MAGAZINE_DETAIL = 'PUBLIC_MAGAZINE_DETAIL'
}
